# Generated by Django 3.0.5 on 2021-01-09 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selections',
            name='ou',
        ),
    ]
